export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_OTP: "/verify-otp",
  DASHBOARD: "/dashboard",
  MENU: "/menu",
  MENU_CREATE: "/menu/create",
  MENU_DETAIL: (id: string | number) => `/menu/${id}`,
  MENU_EDIT: (id: string | number) => `/menu/${id}/edit`,
  ORDERS: "/orders",
  ORDER_DETAIL: (id: string | number) => `/orders/${id}`,
  CHECKOUT: "/checkout",
  CUSTOMERS: "/customers",
  CUSTOMER_DETAIL: (id: string | number) => `/customers/${id}`,
  PROFILE: "/profile",
  SPLASH: "/splash",
  ONBOARDING: "/onboarding",
  STORE: "/store",
  CART: "/cart",
  PAYMENT: "/payment",
  TRACKING: "/tracking",
  LOYALTY: "/loyalty",
  FAVORITES: "/favorites",
  HISTORY: "/history",
  NOTIFICATIONS: "/notifications",
  NOT_FOUND: "/404",
} as const;
